name: gt4sd
channels:
  - https://conda.anaconda.org/pyg
  - https://conda.anaconda.org/pytorch
  - https://conda.anaconda.org/nvidia
  - https://conda.anaconda.org/conda-forge
dependencies:
  - python>=3.7,<3.8
  - pip>=19.1,<20.3
  - pytorch>=1.0
  - pytorch-scatter<=2.0.9
  - pytorch-cluster<=1.6.0
  - pytorch-sparse<=0.6.13
  - pytorch-geometric
  - pip:
      - -r requirements.txt
      - -r vcs_requirements.txt
      # development
      - -r dev_requirements.txt
