name: gt4sd
channels:
  - https://conda.anaconda.org/pytorch
  - https://conda.anaconda.org/nvidia
  - https://conda.anaconda.org/pyg
  - https://conda.anaconda.org/conda-forge
dependencies:
  - python>=3.7,<3.9
  - pip>=19.1,<20.3
  - pytorch>=1.0,<=1.12.1=*cu*
  - pytorch-scatter<=2.0.9=*cu102*
  - torchvision<=0.13.1=*cu*
  - torchaudio<=0.12.1=*cu*
  - pip:
      - -r requirements.txt
      - -r gpu_requirements.txt
      - -r vcs_requirements.txt
      # development
      - -r dev_requirements.txt
