name: gt4sd
channels:
  - https://conda.anaconda.org/pytorch
  - https://conda.anaconda.org/nvidia
  - https://conda.anaconda.org/pyg
  - https://conda.anaconda.org/conda-forge
dependencies:
  - python>=3.7,<3.8
  - pip>=19.1,<20.3
  - cpuonly
  - pytorch>=1.0
  - pyg>=2.0.4
  - pytorch-scatter>=2.0.9
  - pytorch-sparse>=0.6.14
  - pytorch-cluster>=1.6.0
  - pip:
      - -r requirements.txt
      - -r vcs_requirements.txt
      # development
      - -r dev_requirements.txt
