name: CLA Signature
description: Template for issues triggering CLA signature
title: CLA signature
labels:
  - cla-signing
body:
  - type: markdown
    attributes:
      value: |
        Submitting this issue will add you to the list of contributors on the main branch.
        If your pull request (PR) is blocked you may need to merge the main branch into the PR.
  - type: checkboxes
    id: cla
    attributes:
      label: Contributor License Agreement
      options:
        - label: I accept and sign the contributor license agreement ([CLA](https://github.com/GT4SD/gt4sd-core/blob/main/CONTRIBUTING.md#contributor-license-agreement)) to contribute to GT4SD.
          required: true
