name: "Build docs with Sphinx"

on:
  push:
    branches:
      - main
      - ci-setup

jobs:
  docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}  # for conda command
    env:
      # Increase this value to reset cache if conda.yml and requirements.txt
      # have not changed
      CACHE_NUMBER: 0
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda environment
        uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir  # from: conda-incubator/setup-miniconda@v2
          key: conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('conda.yml', 'requirements.txt', 'dev_requirements.txt') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: gt4sd
          environment-file: conda.yml
          auto-activate-base: false
          use-only-tar-bz2: true
      - uses: ammaraskar/sphinx-action@master
        with:
          pre-build-command: conda activate gt4sd && pip install --no-deps .
          docs-folder: "docs/"
      - name: Commit documentation changes
        run: |
          git clone https://github.com/GT4SD/gt4sd --branch gh_pages --single-branch gh_pages
          cp -r docs/_build/html/* gh_pages/
          touch gh_pages/.nojekyll
          cd gh_pages
          git config --local user.email "gt4sd-actions@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "docs: update documentation." -a || true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh_pages
          directory: gh_pages
          github_token: ${{ secrets.GH_TOKEN }}
